### ISSUE TITLE
broken with PyInstaller: ImportError: cannot import name 'EventTypeSpec' from 'quickmachotkey._MinimalHIToolbox'

### ISSUE THREAD

**Issue by Bubba8291** [glyph/QuickMacHotKey#9] opened 2024-09-30 17:13 UTC
```
Traceback (most recent call last):
  File "app.py", line 59, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "quickmachotkey/__init__.py", line 11, in <module>
    __email__ = "lennart-haack@mail.de"
ImportError: cannot import name 'EventTypeSpec' from 'quickmachotkey._MinimalHIToolbox' (./quickmachotkey/_MinimalHIToolbox/__init__.pyc)
```
OS Version: `MacOS 15.0`
Architecture: `arm64` (M2 Chip)
Python Version: `3.11`

**Comment by glyph** [comment] 2024-09-30 21:34
Thanks for the bug report! I'll have a look at this.

**Comment by glyph** [comment] 2024-09-30 22:25
So, a fresh `pip install` on Sequoia with 3.11 works fine.

This appears to be an issue with PyInstaller, or maybe your code that you're bundling with PyInstaller. I can't report it upstream with PyInstaller because I don't have access to your code and cannot reproduce what you are doing.  Line 11 of `quickmachotkey/__init__.py` is not `__email__ = "lennart-haack@mail.de"` so perhaps something else is happening here, but it seems like the most likely problem is that PyInstaller somehow doesn't comply with [PEP 562](https://peps.python.org/pep-0562/), and isn't respecting the `__dir__` and `__getattr__` functions populating the module.

I'm going to close this because I can't reproduce it, but please feel free to re-open with a full example project, either here, or, ideally, on PyInstaller since I think it's actually their bug.

**Closed as not planned by glyph** 2024-09-30 22:25 UTC

**Comment by Bubba8291** [comment] 2024-10-01 06:32
@glyph I believe it has something to do with Ventura though.

Like they got rid of HIToolBox or something since it was deprecated

**Comment by glyph** [comment] 2024-10-01 06:41
> @glyph I believe it has something to do with Ventura though.
> 
> Like they got rid of HIToolBox or something since it was deprecated

I can see why you would think that, but no.  It's a weird non-deprecated non-documented vestigial remnant of a deprecated framework, which, despite it being this way for 10 years, there's still no other alternative for.  My machine is Sequoia, and it still works great on python 3.11, 3.12, and 3.13.

**Comment by glyph** [comment] 2024-10-01 06:43
More to the point though: if HIToolbox were *gone*, you'd get a different error about the framework being missing, and that call to `createFrameworkDirAndGetattr` would fail, rather than the import. The error in your traceback suggests that `getattr_func` is just never getting invoked.
